class CfgWeapons {
    #include "CfgWeapons/base_uniforms.hpp"
    #include "CfgWeapons/combat_long_uniforms.hpp"
    #include "CfgWeapons/combat_long_atacs_uniforms.hpp"
    #include "CfgWeapons/combat_long_plaid_uniforms.hpp"
    #include "CfgWeapons/combat_rolled_uniforms.hpp"
    #include "CfgWeapons/combat_rolled_atacs_uniforms.hpp"
    #include "CfgWeapons/combat_rolled_plaid_uniforms.hpp"
    #include "CfgWeapons/floral_jeans_uniforms.hpp"
    #include "CfgWeapons/floral_shorts_uniforms.hpp"
    #include "CfgWeapons/garment_long_uniforms.hpp"
    #include "CfgWeapons/garment_rolled_uniforms.hpp"
    #include "CfgWeapons/plaid_jeans_uniforms.hpp"
    #include "CfgWeapons/plaid_shorts_uniforms.hpp"
    #include "CfgWeapons/polo_cord_uniforms.hpp"
    #include "CfgWeapons/polo_tactical_uniforms.hpp"
    #include "CfgWeapons/tshirt_jeans_uniforms.hpp"
    #include "CfgWeapons/vip_suit_uniforms.hpp"

};
