class CfgWeapons {
    #include "uniforms\base.hpp"
    #include "uniforms\combat_long.hpp"
    #include "uniforms\combat_long_atacs.hpp"
    #include "uniforms\combat_long_auscam.hpp"
    #include "uniforms\combat_long_plaid.hpp"
    #include "uniforms\combat_rolled.hpp"
    #include "uniforms\combat_rolled_atacs.hpp"
    #include "uniforms\combat_rolled_auscam.hpp"
    #include "uniforms\combat_rolled_plaid.hpp"
    #include "uniforms\floral_jeans.hpp"
    #include "uniforms\floral_shorts.hpp"
    #include "uniforms\garment_long.hpp"
    #include "uniforms\garment_rolled.hpp"
    #include "uniforms\heli_pilot_coveralls.hpp"
    #include "uniforms\plaid_jeans.hpp"
    #include "uniforms\plaid_shorts.hpp"
    #include "uniforms\polo_cord.hpp"
    #include "uniforms\polo_tactical.hpp"
    #include "uniforms\tshirt_jeans.hpp"
    #include "uniforms\vip_suit.hpp"
};
