class CargoTurret;
class Turrets: Turrets {
    class MainTurret: MainTurret {
        body = "mainTurret";
        gun = "mainGun";
        viewGunnerInExternal = 1;
        minElev = -30;
        maxElev = 45;
        initElev = 0;
        soundServo[] = {"", db-40, 1};
        stabilizedInAxes = StabilizedInAxesBoth;
        gunBeg = "muzzle_1";
        gunEnd = "chamber_1";
        weapons[] = {QCLASS(LMG_Minigun_SUV)};
        maxHorizontalRotSpeed = 1.8;
        maxVerticalRotSpeed = 1.8;
        magazines[] = {"2000Rnd_65x39_Belt_Tracer_Red"};
        gunnerRightHandAnimName = "OtocHlavenSUV";
        gunnerLeftHandAnimName = "OtocHlavenSUV";
        animationSourceHatch = "close_cover_source";
        gunnerInAction = "Arcadian_GunnerTurnIn";
        gunnerAction = "Arcadian_GunnerTurnOut";
        gunnerOpticsModel = "";
        gunnerOutOpticsModel = "\a3\weapons_f\reticle\optics_empty";
        memoryPointGunnerOutOptics = "gunnerview";
        memoryPointGunnerOptics = "";
        memoryPointsGetInGunner = "pos cargo rear";
        memoryPointsGetInGunnerDir = "pos cargo dir rear";
        outGunnerMayFire = 1;
        startEngine = 0;
        inGunnerMayFire = 0;
        LODTurnedIn = 1000;
        LODOpticsIn = 1000;
        LODTurnedOut = 1000;
        LODOpticsOut = 1000;
        canhideGunner = 1;
        castGunnerShadow = 1;
        hideProxyInCombat = 0;
        forceHideGunner = 0;
        gunnerCompartments = "Compartment1";
        class ViewOptics: ViewOptics {
            minFov = 0.25;
            maxFov = 1.25;
            initFov = 0.75;
        };
        class ViewGunner: ViewOptics {};
    };

    class CargoTurret_1: CargoTurret {
        minElev = -10;
        maxElev = 23;
        maxTurn = 130;
        minTurn = 25;
        gunnerAction = "passenger_flatground_2";
        gunnerName = "$str_a3_rear_gunner";
        proxyIndex = 6;
        LODTurnedIn = 1000;
        LODOpticsIn = 1000;
        LODTurnedOut = 1000;
        LODOpticsOut = 1000;
        isPersonTurret = 1;
        memoryPointsGetInGunner = "pos cargo rear";
        memoryPointsGetInGunnerDir = "pos cargo dir rear";
        memoryPointGunnerOptics = "";
        gunnerOutOpticsModel = "";
        gunnerOpticsModel = "";
        enabledByAnimationSource = "reardoor_2_source";
        usepip = 0;
        ejectDeadGunner = 1;
        startEngine = 0;
        outGunnerMayFire = 1;
        inGunnerMayFire = 0;
        commanding = -2;
        gunnerCompartments = "Compartment1";
    };
};
