#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            QCLASS(Unit_Long_Black),
            QCLASS(Unit_Long_Earth),
            QCLASS(Unit_Long_Pattern_Foliage),
            QCLASS(Unit_Long_Plaid_Black),
            QCLASS(Unit_Long_Plaid_Black2),
            QCLASS(Unit_Long_Plaid_Buffalo),
            QCLASS(Unit_Long_Plaid_Buffalo2),
            QCLASS(Unit_Long_Plaid_Earth),
            QCLASS(Unit_Long_Plaid_Earth2),
            QCLASS(Unit_Long_Plaid_Earth3),
            QCLASS(Unit_Long_Plaid_Foliage),
            QCLASS(Unit_Long_Plaid_Foliage2),
            QCLASS(Unit_Long_Plaid_Foliage3),
            QCLASS(Unit_Long_Plaid_MacMillan_Ancient),
            QCLASS(Unit_Long_Plaid_Melville_2_Black_Lines),
            QCLASS(Unit_Long_Plaid_MacMillan_Hunting_Ancient),
            QCLASS(Unit_Long_Plaid_MacMillan_Dress),
            QCLASS(Unit_Long_Plaid_Melville),
            QCLASS(Unit_Long_Black_Kneepads),
            QCLASS(Unit_Long_Earth_Kneepads),
            QCLASS(Unit_Long_Foliage_Kneepads),
            QCLASS(Unit_Long_Pattern_Foliage_Kneepads),
            QCLASS(Unit_Long_Plaid_Black_Kneepads),
            QCLASS(Unit_Long_Plaid_Black2_Kneepads),
            QCLASS(Unit_Long_Plaid_Buffalo_Kneepads),
            QCLASS(Unit_Long_Plaid_Buffalo2_Kneepads),
            QCLASS(Unit_Long_Plaid_Earth_Kneepads),
            QCLASS(Unit_Long_Plaid_Earth2_Kneepads),
            QCLASS(Unit_Long_Plaid_Earth3_Kneepads),
            QCLASS(Unit_Long_Plaid_Foliage_Kneepads),
            QCLASS(Unit_Long_Plaid_Foliage2_Kneepads),
            QCLASS(Unit_Long_Plaid_Foliage3_Kneepads),
            QCLASS(Unit_Long_Plaid_MacMillan_Ancient_Kneepads),
            QCLASS(Unit_Long_Plaid_Melville_2_Black_Lines_Kneepads),
            QCLASS(Unit_Long_Plaid_MacMillan_Hunting_Ancient_Kneepads),
            QCLASS(Unit_Long_Plaid_MacMillan_Dress_Kneepads),
            QCLASS(Unit_Long_Plaid_Melville_Kneepads),
            QCLASS(Unit_Rolled_Black),
            QCLASS(Unit_Rolled_Earth),
            QCLASS(Unit_Rolled_Pattern_Foliage),
            QCLASS(Unit_Rolled_Plaid_Black),
            QCLASS(Unit_Rolled_Plaid_Black2),
            QCLASS(Unit_Rolled_Plaid_Buffalo),
            QCLASS(Unit_Rolled_Plaid_Buffalo2),
            QCLASS(Unit_Rolled_Plaid_Earth),
            QCLASS(Unit_Rolled_Plaid_Earth2),
            QCLASS(Unit_Rolled_Plaid_Earth3),
            QCLASS(Unit_Rolled_Plaid_Foliage),
            QCLASS(Unit_Rolled_Plaid_Foliage2),
            QCLASS(Unit_Rolled_Plaid_Foliage3),
            QCLASS(Unit_Rolled_Plaid_MacMillan_Ancient),
            QCLASS(Unit_Rolled_Plaid_Melville_2_Black_Lines),
            QCLASS(Unit_Rolled_Plaid_MacMillan_Hunting_Ancient),
            QCLASS(Unit_Rolled_Plaid_MacMillan_Dress),
            QCLASS(Unit_Rolled_Plaid_Melville),
            QCLASS(Unit_Rolled_Black_Kneepads),
            QCLASS(Unit_Rolled_Earth_Kneepads),
            QCLASS(Unit_Rolled_Pattern_Foliage_Kneepads),
            QCLASS(Unit_Rolled_Plaid_Black_Kneepads),
            QCLASS(Unit_Rolled_Plaid_Black2_Kneepads),
            QCLASS(Unit_Rolled_Plaid_Buffalo_Kneepads),
            QCLASS(Unit_Rolled_Plaid_Buffalo2_Kneepads),
            QCLASS(Unit_Rolled_Plaid_Earth_Kneepads),
            QCLASS(Unit_Rolled_Plaid_Earth2_Kneepads),
            QCLASS(Unit_Rolled_Plaid_Earth3_Kneepads),
            QCLASS(Unit_Rolled_Plaid_Foliage_Kneepads),
            QCLASS(Unit_Rolled_Plaid_Foliage2_Kneepads),
            QCLASS(Unit_Rolled_Plaid_Foliage3_Kneepads),
            QCLASS(Unit_Rolled_Plaid_MacMillan_Ancient_Kneepads),
            QCLASS(Unit_Rolled_Plaid_Melville_2_Black_Lines_Kneepads),
            QCLASS(Unit_Rolled_Plaid_MacMillan_Hunting_Ancient_Kneepads),
            QCLASS(Unit_Rolled_Plaid_MacMillan_Dress_Kneepads),
            QCLASS(Unit_Rolled_Plaid_Melville_Kneepads)
        };
        weapons[] = {
            QCLASS(Uniform_Long_Black),
            QCLASS(Uniform_Long_Earth),
            QCLASS(Uniform_Long_Pattern_Foliage),
            QCLASS(Uniform_Long_Plaid_Black),
            QCLASS(Uniform_Long_Plaid_Black2),
            QCLASS(Uniform_Long_Plaid_Buffalo),
            QCLASS(Uniform_Long_Plaid_Buffalo2),
            QCLASS(Uniform_Long_Plaid_Earth),
            QCLASS(Uniform_Long_Plaid_Earth2),
            QCLASS(Uniform_Long_Plaid_Earth3),
            QCLASS(Uniform_Long_Plaid_Foliage),
            QCLASS(Uniform_Long_Plaid_Foliage2),
            QCLASS(Uniform_Long_Plaid_Foliage3),
            QCLASS(Uniform_Long_Plaid_MacMillan_Ancient),
            QCLASS(Uniform_Long_Plaid_Melville_2_Black_Lines),
            QCLASS(Uniform_Long_Plaid_MacMillan_Hunting_Ancient),
            QCLASS(Uniform_Long_Plaid_MacMillan_Dress),
            QCLASS(Uniform_Long_Plaid_Melville),
            QCLASS(Uniform_Long_Black_Kneepads),
            QCLASS(Uniform_Long_Earth_Kneepads),
            QCLASS(Uniform_Long_Foliage_Kneepads),
            QCLASS(Uniform_Long_Pattern_Foliage_Kneepads),
            QCLASS(Uniform_Long_Plaid_Black_Kneepads),
            QCLASS(Uniform_Long_Plaid_Black2_Kneepads),
            QCLASS(Uniform_Long_Plaid_Buffalo_Kneepads),
            QCLASS(Uniform_Long_Plaid_Buffalo2_Kneepads),
            QCLASS(Uniform_Long_Plaid_Earth_Kneepads),
            QCLASS(Uniform_Long_Plaid_Earth2_Kneepads),
            QCLASS(Uniform_Long_Plaid_Earth3_Kneepads),
            QCLASS(Uniform_Long_Plaid_Foliage_Kneepads),
            QCLASS(Uniform_Long_Plaid_Foliage2_Kneepads),
            QCLASS(Uniform_Long_Plaid_Foliage3_Kneepads),
            QCLASS(Uniform_Long_Plaid_MacMillan_Ancient_Kneepads),
            QCLASS(Uniform_Long_Plaid_Melville_2_Black_Lines_Kneepads),
            QCLASS(Uniform_Long_Plaid_MacMillan_Hunting_Ancient_Kneepads),
            QCLASS(Uniform_Long_Plaid_MacMillan_Dress_Kneepads),
            QCLASS(Uniform_Long_Plaid_Melville_Kneepads),
            QCLASS(Uniform_Rolled_Black),
            QCLASS(Uniform_Rolled_Earth),
            QCLASS(Uniform_Rolled_Pattern_Foliage),
            QCLASS(Uniform_Rolled_Plaid_Black),
            QCLASS(Uniform_Rolled_Plaid_Black2),
            QCLASS(Uniform_Rolled_Plaid_Buffalo),
            QCLASS(Uniform_Rolled_Plaid_Buffalo2),
            QCLASS(Uniform_Rolled_Plaid_Earth),
            QCLASS(Uniform_Rolled_Plaid_Earth2),
            QCLASS(Uniform_Rolled_Plaid_Earth3),
            QCLASS(Uniform_Rolled_Plaid_Foliage),
            QCLASS(Uniform_Rolled_Plaid_Foliage2),
            QCLASS(Uniform_Rolled_Plaid_Foliage3),
            QCLASS(Uniform_Rolled_Plaid_MacMillan_Ancient),
            QCLASS(Uniform_Rolled_Plaid_Melville_2_Black_Lines),
            QCLASS(Uniform_Rolled_Plaid_MacMillan_Hunting_Ancient),
            QCLASS(Uniform_Rolled_Plaid_MacMillan_Dress),
            QCLASS(Uniform_Rolled_Plaid_Melville),
            QCLASS(Uniform_Rolled_Black_Kneepads),
            QCLASS(Uniform_Rolled_Earth_Kneepads),
            QCLASS(Uniform_Rolled_Pattern_Foliage_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_Black_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_Black2_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_Buffalo_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_Buffalo2_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_Earth_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_Earth2_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_Earth3_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_Foliage_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_Foliage2_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_Foliage3_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_MacMillan_Ancient_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_Melville_2_Black_Lines_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_MacMillan_Hunting_Ancient_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_MacMillan_Dress_Kneepads),
            QCLASS(Uniform_Rolled_Plaid_Melville_Kneepads)
        };
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"tacs_units", "CUP_Creatures_Military_PMC", "CUP_Creatures_Military_Germany"};
        skipWhenMissingDependencies = 1;
        author = ECSTRING(main,Author);
        authors[] = {"GilleeDoo", "Mike"};
        url = ECSTRING(main,URL);
        VERSION_CONFIG;
    };
};

#include "CfgVehicles.hpp"
#include "CfgWeapons.hpp"
